name: urbanminded_assessment
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


  cupertino_icons: ^1.0.2

  #===============
  # main packages
  #==============
  # A Dart package that helps to implement value
  # based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.3


  #  ============= State Management ==================

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2



  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^6.0.2

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  # Built to be used with the bloc state management package.
  flutter_bloc: ^8.0.1

  # A powerful Http client for Dart, which supports Interceptors,
  # FormData, Request Cancellation, File Downloading, Timeout etc
  dio: ^4.0.6
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1





  #  ============= Useful Utils ==================

  # Toast Library for Flutter, Easily create toast messages in single line of code
  fluttertoast: ^8.0.9

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, data/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0
  intl_utils: ^2.6.1

  path_provider: ^2.0.1


  # for dependency injection
  injectable: ^1.4.1
  get_it:

  # A Flutter package that can be used to extract the locales that are currently defined on a device with the current locale set as the first in the list.
  devicelocale: ^0.5.0



  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.13


  # Flutter plugin providing detailed information about the device (make, model, etc.),
  # and Android or iOS version the app is running on.
  device_info_plus: ^3.2.3
  # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
  uuid: ^3.0.6




  # A pure Dart library that checks for internet by opening a socket to a list of specified addresses,
  # each with individual port and timeout. Defaults are provided for convenience.
  internet_connection_checker: ^0.0.1+3

  # Easily make Flutter apps responsive.
  # Automatically adapt UI to different screen sizes.
  # Responsiveness made simple.
  responsive_framework: ^0.1.7



  #  ============= UI Helper ==================
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^2.0.0

  # A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
  flutter_slidable: ^1.2.0


  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.0.0+2

  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.1.0

  # An SVG rendering and widget library for Flutter,
  # which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^1.0.3


  #Flutter library to load and cache error images.
  #Can also be used with placeholder and error widgets.
  cached_network_image: ^3.2.0

  #Flutter Page Transition Package which is the transition second page
  page_transition: ^2.0.5

  # Beautiful animations inspired on Animate.css,
  # every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^2.0.0

  # Easily add staggered animations to your ListView,
  # GridView, Column and Row children as shown in Material Design guidelines
  flutter_staggered_animations: ^1.0.0

  # Fancy pre-built animations that can easily be integrated into any Flutter application.
  animations: ^2.0.2

  #A modal progress indicator widget
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

  # A flexible widget for user notification.
  # Customize your text, button, duration, animations and much more.
  # For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.10.28


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  analyzer: ^3.4.1






flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  main_local: en
  enabled: true
  class_name: Translations
  arb_dir: lib/core/managers/localization/res
  output_dir: lib/core/managers/localization/generated